"""Add workout template support

Revision ID: 492ed2b78a4d
Revises: 4d452487a4d2
Create Date: 2025-05-27 14:55:44.703329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '492ed2b78a4d'
down_revision = '4d452487a4d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_template', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('template_category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('difficulty_level', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('estimated_duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('equipment_needed', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('target_muscle_groups', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_plan', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('target_muscle_groups')
        batch_op.drop_column('equipment_needed')
        batch_op.drop_column('estimated_duration')
        batch_op.drop_column('difficulty_level')
        batch_op.drop_column('template_category')
        batch_op.drop_column('is_template')

    # ### end Alembic commands ###
