"""Add GIF URL and common notes to exercises

Revision ID: 4d452487a4d2
Revises: 75ac3c5d66e2
Create Date: 2025-05-27 14:27:13.185935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d452487a4d2'
down_revision = '75ac3c5d66e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gif_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('common_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.drop_column('common_notes')
        batch_op.drop_column('gif_url')

    # ### end Alembic commands ###
