"""Add PR fields and automatic PB tracking

Revision ID: 74038cf5b1ee
Revises: aea6b3a5f208
Create Date: 2025-05-27 11:43:26.265057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74038cf5b1ee'
down_revision = 'aea6b3a5f208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_pr', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('pr_description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_log', schema=None) as batch_op:
        batch_op.drop_column('pr_description')
        batch_op.drop_column('is_pr')

    # ### end Alembic commands ###
